services:
  ironmount-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ironmount
    restart: unless-stopped
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    environment:
      - NODE_ENV=development
    ports:
      - "4096:4097"
    volumes:
      - /var/lib/ironmount:/var/lib/ironmount

      - ./apps/client/app:/app/apps/client/app
      - ./apps/server/src:/app/apps/server/src

  ironmount-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: ironmount
    restart: unless-stopped
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    ports:
      - "4096:4096"
    volumes:
      - /var/lib/ironmount/:/var/lib/ironmount/
