services:
  ironmount-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ironmount
    restart: unless-stopped
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    environment:
      - NODE_ENV=development
    ports:
      - "4096:4096"
    volumes:
      - /var/lib/ironmount:/var/lib/ironmount

      - ./app:/app/app
      - ~/.config/rclone:/root/.config/rclone

  ironmount-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: ironmount
    restart: unless-stopped
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    ports:
      - "4096:4096"
    volumes:
      - /var/lib/ironmount:/var/lib/ironmount:rshared
      - /run/docker/plugins:/run/docker/plugins
      - /var/run/docker.sock:/var/run/docker.sock
